# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.10

EAPI=8

inherit cargo git-r3

DESCRIPTION="A git prepare-commit-msg hook for summarizing commits with LLMs."
HOMEPAGE="https://github.com/zurawiki/gptcommit"
EGIT_REPO_URI="https://github.com/zurawiki/gptcommit.git"
EGIT_BRANCH="main"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}
